#!groovy

node('master') {
    stage('Install Dependencies') {
        sh 'echo install dependencies'
    }
    stage('Build') {
        sh 'echo build app'
    }
    stage('Test') {
        sh 'echo test app'
    }
}