#!groovy

pipeline {
    agent {
        label 'master'
    }
    stages {
        stage('Install') {
            steps {
                sh 'make install'
            }
        }
        stage('Build') {
            steps {
                sh 'make build'
            }
        }
        stage('Lint') {
            steps {
                sh 'make lint'
            }
        }
        stage('Test') {
            steps {
                sh 'make test'
                sh 'make coverage'
                sh 'make clean'
            }
        }
    }
}