#!groovy

pipeline {
    agent {
        label 'master'
    }
    stages {
        stage('Build') {
            steps {
                //sh 'make build'
            }
        }
        stage('Lint') {
            steps {
                //sh 'make lint'
            }
        }
        stage('Test') {
            steps {
                sh 'go test -cover -coverprofile=${TEST_DIR}/coverage.out'
                //sh 'make test'
                //sh 'make coverage'
                //sh 'make clean'
            }
        }
    }
}